//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocionicTeamBuilder.Mobile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocionicTeamBuilder.Mobile.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string BadMood {
            get {
                return ResourceManager.GetString("BadMood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string BlacklistTitle {
            get {
                return ResourceManager.GetString("BlacklistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing password.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date range.
        /// </summary>
        public static string DateRangeLbl {
            get {
                return ResourceManager.GetString("DateRangeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date time.
        /// </summary>
        public static string DateTimeLbl {
            get {
                return ResourceManager.GetString("DateTimeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsBtn {
            get {
                return ResourceManager.GetString("DetailsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details (optional).
        /// </summary>
        public static string DetailsLbl {
            get {
                return ResourceManager.GetString("DetailsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s data.
        /// </summary>
        public static string EmployeeInfoTitle {
            get {
                return ResourceManager.GetString("EmployeeInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EmployeesTitle {
            get {
                return ResourceManager.GetString("EmployeesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        public static string ExitBtn {
            get {
                return ResourceManager.GetString("ExitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really wanna to exit from the test? Your answers won&apos;t be saved..
        /// </summary>
        public static string ExitTestMsg {
            get {
                return ResourceManager.GetString("ExitTestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit from the test.
        /// </summary>
        public static string ExitTestTitle {
            get {
                return ResourceManager.GetString("ExitTestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My feedback.
        /// </summary>
        public static string FeedbackBtn {
            get {
                return ResourceManager.GetString("FeedbackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string GoodMood {
            get {
                return ResourceManager.GetString("GoodMood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great.
        /// </summary>
        public static string GreatMood {
            get {
                return ResourceManager.GetString("GreatMood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat.
        /// </summary>
        public static string HeartBeatLbl {
            get {
                return ResourceManager.GetString("HeartBeatLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all of the fields..
        /// </summary>
        public static string InvalidInputFillMsg {
            get {
                return ResourceManager.GetString("InvalidInputFillMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check new password, you entered different values..
        /// </summary>
        public static string InvalidInputNewPassMsg {
            get {
                return ResourceManager.GetString("InvalidInputNewPassMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check old password, it&apos;s incorrect..
        /// </summary>
        public static string InvalidInputOldPassMsg {
            get {
                return ResourceManager.GetString("InvalidInputOldPassMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is the same as old one..
        /// </summary>
        public static string InvalidInputSamePassMsg {
            get {
                return ResourceManager.GetString("InvalidInputSamePassMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string InvalidInputTitle {
            get {
                return ResourceManager.GetString("InvalidInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My IoT data.
        /// </summary>
        public static string IotDataBtn {
            get {
                return ResourceManager.GetString("IotDataBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT data.
        /// </summary>
        public static string IotDataTitle {
            get {
                return ResourceManager.GetString("IotDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ID for the IoT-device is .
        /// </summary>
        public static string IotIdMsg {
            get {
                return ResourceManager.GetString("IotIdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jung dichotomies: .
        /// </summary>
        public static string JungDichotomies {
            get {
                return ResourceManager.GetString("JungDichotomies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with such login and password..
        /// </summary>
        public static string LoginFailMsg {
            get {
                return ResourceManager.GetString("LoginFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string LoginFailTitle {
            get {
                return ResourceManager.GetString("LoginFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mood.
        /// </summary>
        public static string MoodLbl {
            get {
                return ResourceManager.GetString("MoodLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee.
        /// </summary>
        public static string NewEmployeeTitle {
            get {
                return ResourceManager.GetString("NewEmployeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add feedback.
        /// </summary>
        public static string NewFeedbackTitle {
            get {
                return ResourceManager.GetString("NewFeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoBtn {
            get {
                return ResourceManager.GetString("NoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass testing.
        /// </summary>
        public static string PassTestingBtn {
            get {
                return ResourceManager.GetString("PassTestingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudonym: .
        /// </summary>
        public static string Pseudonym {
            get {
                return ResourceManager.GetString("Pseudonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string PulseLbl {
            get {
                return ResourceManager.GetString("PulseLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainin signs: .
        /// </summary>
        public static string RaininSigns {
            get {
                return ResourceManager.GetString("RaininSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such login already exists, it should be unique..
        /// </summary>
        public static string SaveFailMsg {
            get {
                return ResourceManager.GetString("SaveFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string SaveFailTitle {
            get {
                return ResourceManager.GetString("SaveFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was saved.
        /// </summary>
        public static string SaveSuccessMsg {
            get {
                return ResourceManager.GetString("SaveSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SaveSuccessTitle {
            get {
                return ResourceManager.GetString("SaveSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try later..
        /// </summary>
        public static string SendFeedbackFailMsg {
            get {
                return ResourceManager.GetString("SendFeedbackFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small group: .
        /// </summary>
        public static string SmallGroup {
            get {
                return ResourceManager.GetString("SmallGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string SocionicDescription {
            get {
                return ResourceManager.GetString("SocionicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string SocionicName {
            get {
                return ResourceManager.GetString("SocionicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socionic Type.
        /// </summary>
        public static string SocionicType {
            get {
                return ResourceManager.GetString("SocionicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socionic Type.
        /// </summary>
        public static string SocionicTypeTitle {
            get {
                return ResourceManager.GetString("SocionicTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your socionic type is undefined. Pass testing to know smth new about yourself..
        /// </summary>
        public static string SocionicTypeUndefinedMsg {
            get {
                return ResourceManager.GetString("SocionicTypeUndefinedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So-so.
        /// </summary>
        public static string SoSoMood {
            get {
                return ResourceManager.GetString("SoSoMood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the task you are interested in.
        /// </summary>
        public static string TasksLbl {
            get {
                return ResourceManager.GetString("TasksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TasksTitle {
            get {
                return ResourceManager.GetString("TasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My team.
        /// </summary>
        public static string TeamTitle {
            get {
                return ResourceManager.GetString("TeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string TemperatureLbl {
            get {
                return ResourceManager.GetString("TemperatureLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string TestingTitle {
            get {
                return ResourceManager.GetString("TestingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test passing.
        /// </summary>
        public static string TestPassingTitle {
            get {
                return ResourceManager.GetString("TestPassingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your socionic type is .
        /// </summary>
        public static string TestResMsg {
            get {
                return ResourceManager.GetString("TestResMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing result.
        /// </summary>
        public static string TestResTitle {
            get {
                return ResourceManager.GetString("TestResTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way of building.
        /// </summary>
        public static string WayOfBuildingLbl {
            get {
                return ResourceManager.GetString("WayOfBuildingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web site.
        /// </summary>
        public static string WelcomeBtn {
            get {
                return ResourceManager.GetString("WelcomeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can visit our web-site: .
        /// </summary>
        public static string WelcomeTxt {
            get {
                return ResourceManager.GetString("WelcomeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working profile: .
        /// </summary>
        public static string WorkingProfile {
            get {
                return ResourceManager.GetString("WorkingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesBtn {
            get {
                return ResourceManager.GetString("YesBtn", resourceCulture);
            }
        }
    }
}
